export type {
  Guest,
  CreateGuestDto,
  UpdateGuestDto,
  Property,
  CreatePropertyDto,
  UpdatePropertyDto,
  Room,
  RoomStatus,
  CreateRoomDto,
  UpdateRoomDto,
  RoomType,
  CreateRoomTypeDto,
  UpdateRoomTypeDto,
  Reservation,
  ReservationStatus,
  CreateReservationDto,
  UpdateReservationDto,
} from '@/lib/api';
